name: Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t sample-nodejs .

    - name: Login to ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 454143665149.dkr.ecr.ap-south-1.amazonaws.com

    - name: Tag Docker Image
      run: docker tag sample-nodejs:latest 454143665149.dkr.ecr.ap-south-1.amazonaws.com/sample-nodejs:latest

    - name: Push to ECR
      run: docker push 454143665149.dkr.ecr.ap-south-1.amazonaws.com/sample-nodejs:latest
